version: '3'

services:
  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: vikunja
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
  api:
    image: vikunja/vikunja
    environment:
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: $VIKUNJA_DATABASE_PASSWORD
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: $VIKUNJA_SERVICE_JWTSECRET
      VIKUNJA_SERVICE_PUBLICURL: https://pi-apps.chicken-stork.ts.net:10011/
      VIKUNJA_MAILER_ENABLED: true
      VIKUNJA_MAILER_HOST: email-smtp.eu-west-1.amazonaws.com
      VIKUNJA_MAILER_PORT: 587
      VIKUNJA_MAILER_USERNAME: $VIKUNJA_MAILER_USERNAME
      VIKUNJA_MAILER_PASSWORD: $VIKUNJA_MAILER_PASSWORD
      VIKUNJA_MAILER_FROMEMAIL: vikunja@notifications.alexchesters.com
      VIKUNJA_LOG_MAIL: stdout
      VIKUNJA_LOG_MAILLEVEL: INFO
    ports:
      - 3456:3456
    volumes:
      - files:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped

volumes:
  database:
  files:
